id: P010662
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN2447
  title: གཟུངས་བསྡུས།
  author: ''
  volumes:
    5cd8e3b78fcf4cb4a5980ef080bd4851:
      image_group_id: I3CN2449
      title: ''
      volume_number: 1
      total_pages: 1632
      base_file: v001.txt
