id: I38905B43
legacy_id: P010662
ocr_import_info:
  bdrc_scan_id: W3CN2447
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T02:43:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:08:34.609058+00:00'
last_modified: 2022-09-03 21:09:17.765514
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2447
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2447
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཟུངས་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.561240058338609
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I3CN2449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2449
      total_pages: 1632
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2449.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.561240058338609
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
